version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/src/"
    target-branch: "develop"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/src/"
    target-branch: "develop"
    schedule:
      interval: "daily"